import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/theme-provider";

import Header from "@/app/component/Header";
import { ModeToggle } from "@/components/ModeToggle";
import AppProvider from "./AppProvider";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Header initialSessionToken={sessionToken?.value}/>
        <Toaster />
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <AppProvider initialSessionToken={sessionToken?.value}>{children}</AppProvider>
          <ModeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
